# Generated by Django 4.2.9 on 2024-01-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="page", old_name="categort", new_name="category",
        ),
    ]
