# Generated by Django 4.2.9 on 2024-01-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0003_category_likes_category_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
